### ISSUE TITLE
游戏内截图转发

### ISSUE THREAD

**Issue by Shigma** [obstudio/MC-Repeater#1]
Minecraft 中当玩家按下 F2 时默认行为是截图。我觉得可以借助内置的截图功能，加入快捷按键使得截图可以转发到群内。

**Comment by NN708** [comment]
这个应该是客户端的行为，而不是 MC 服务端，但是转发只有在服务端上才能实现。你对具体的实现有什么想法吗？

**Comment by Shigma** [comment]
好吧我想得太简单了，这里的确很是麻烦……
