### ISSUE TITLE
掉线防抖机制

### ISSUE THREAD

**Issue by Shigma** [obstudio/MC-Repeater#3]
由于网络或游戏机制等原因，游戏中可能会出现不必要的连续下线和上线提示。建议加入掉线防抖机制。

具体实现：
- 在 config 中加入 `offlineTimeout` 选项，用于表示最小界定为下线的时间
- 加入一个全局数组 `offlinePlayers`，其元素是下线玩家的 id。
- 当某位玩家发生下线事件时，向数组中添加玩家 id 并等待 `offlineTimeout` 秒，如果期间发生了同一玩家上线事件，则清除此 id。等待结束后检查数组中是否有此 id，如果有则删去此 id 并向 bot 服务器发送此下线事件。

**Comment by NN708** [comment]
这个最主要的问题可能是服务器数据发送量会有限制，MC-Repeater 中实现的话只能是个可选选项，默认不会开启。如果在服务端实现，可能可以做到根据服务端实际情况来限制发送量，而不是由用户决定。

你觉得是在 MC-Repeater 中实现更好，还是在服务端实现更好？

**Comment by Shigma** [comment]
相比 #4，我觉得这个更像是游戏本身的问题。如果说其他游戏不一定会出现我上面所说的情况的话，把这个逻辑放在 repeater 中就比较容易理解了。
