### ISSUE TITLE
推送信息节流机制

### ISSUE THREAD

**Issue by Shigma** [obstudio/MC-Repeater#4]
为了防止大量的网络请求带来的性能损耗，建议对发送的信息进行节流。

具体实现：

- 在 config 中加入 `throttleInterval` 选项，用于表示最小发送信息的间隔
- 加入一个全局字符串 `messageBuffer`，初始化为空串。
- 当要发送某个信息时，将要发送的文本接在 `messageBuffer` 之后。
- 设定一个定期任务，每隔 `throttleInterval` 秒检查一次 `messageBuffer` 中的文本，如果非空则发送并清空之。

**Comment by NN708** [comment]
可以考虑，尤其是如果加入完整的 log 转发功能的话，可能确实有必要合并发送。

一个问题是，服务端要如何把一次发送中的不同消息分开？

**Comment by Shigma** [comment]
可以采用单纯的 `\n` 分隔，甚至不分隔我觉得都是可以理解的。

**Comment by Shigma** [comment]
Closed by #5
